import { BillingCycleStatus } from './entities/billing-cycle-version.entity';
import { UpdateBillingCycleDto } from './dto/billing-cycle.dto';

export const BILLING_CYCLE_AUDIT_MODULE_NAME = 'billing_cycles';

export const BILLING_CYCLE_CHANGE_REASON_LOV_CATEGORY = 'BILLING_CYCLE_CHANGE_REASON';
export const BILLING_CYCLE_DEPRECATION_REASON_LOV_CATEGORY = 'BILLING_CYCLE_DEPRECATION_REASON';

export enum BillingCycleAuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  RESUBMIT = 'RESUBMIT',
  CREATE_VERSION = 'CREATE_VERSION',
  SCHEDULE_DEPRECATION = 'SCHEDULE_DEPRECATION',
  DEPRECATE = 'DEPRECATE',
  AUTO_ACTIVATE = 'AUTO_ACTIVATE',
  AUTO_DEPRECATE = 'AUTO_DEPRECATE',
}

export const DEFAULT_BILL_GENERATION_DAYS_ATTRIBUTE_KEY = 'BILLING_CYCLE_DEFAULT_BILL_GENERATION_DAYS';
export const DEFAULT_BILL_ISSUE_DAYS_ATTRIBUTE_KEY = 'BILLING_CYCLE_DEFAULT_BILL_ISSUE_DAYS';
export const DEFAULT_BILL_DUE_DAYS_ATTRIBUTE_KEY = 'BILLING_CYCLE_DEFAULT_BILL_DUE_DAYS';
export const REQUIRE_CHANGE_REASON_ON_EDIT_ATTRIBUTE_KEY = 'REQUIRE_CHANGE_REASON_ON_EDIT';

export const EDITABLE_BILLING_CYCLE_STATUSES = new Set([
  BillingCycleStatus.INACTIVE,
  BillingCycleStatus.ACTIVE,
  BillingCycleStatus.REJECTED,
]);

export const LOCKED_BILLING_CYCLE_FIELDS: (keyof UpdateBillingCycleDto)[] = ['readingStartDay', 'readingEndDay'];

export const NEW_VERSION_SOURCE_STATUSES = new Set([BillingCycleStatus.ACTIVE, BillingCycleStatus.INACTIVE]);
