export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  OPERATIONS: 'OPERATIONS',
  BILLING: 'BILLING',
  FINANCE:'FINANCE',
  CUSTOMER_SUPPORT: 'CUSTOMER_SUPPORT',
  CUSTOMER: 'CUSTOMER',
} as const;

